export const products = [
  // Nothing Phone 1 - White
  {
    _id: "1",
    itemName: "Nothing Special Phone 1",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI2Vx6Sgporz_L_4rm_QbRrNNKXa7uLPkZfw&usqp=CAU",
    description:
      "Designed with impressive features and a myriad of thought processes put together ",
    rating: 4,
    reviews: 50,
    color: "White",
    storage: "8GB 128GB",
    category: "Mobile",
    oldPrice: 89999.99,
    newPrice: 49999.99,
    discount: 22,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false,
    qty: 1,
  },
  {
    _id: "2",
    itemName: "Nothing Economy Phone 1",
    image:
      "https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/l/s/n/-original-imagrdeframtgucc.jpeg?q=70",
    description: "A high-end smartphone with cutting-edge features.",
    rating: 4,
    reviews: 50,
    color: "Black",
    storage: "8GB 128GB",
    category: "Mobile",
    oldPrice: 89990.99,
    newPrice: 69990.99,
    discount: 22,
    isTrending: false,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: false,
    qty: 1,
  },
  // More variants for Nothing Phone 1 can be added here...

  // Nothing Phone 2 - White
  {
    _id: "3",
    itemName: "Nothing Stylish Phone 2",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaAQ3GVpfJGiK62r6vPtZ3UFmxyYmjmA6nvFCJusJLRMkcIRXI04rGUgd5-lsk6mxV9pU&usqp=CAU",
    description: "An innovative smartphone with powerful specifications.",
    rating: 3.4,
    reviews: 40,
    color: "White",
    storage: "12GB 256GB",
    category: "Mobile",
    oldPrice: 100099.99,
    newPrice: 89999.99,
    discount: 18,
    isTrending: false,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: true,
    qty: 1,
  },
  {
    _id: "4",
    itemName: "Nothing PLus Phone 2",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaBRrGsiVVnlki4KoKILEQNca7JOqvZItdzA&usqp=CAU",
    description: "An innovative smartphone with powerful specifications.",
    rating: 4,
    reviews: 40,
    color: "White",
    storage: "12GB 128GB",
    category: "Mobile",
    oldPrice: 199999.99,
    newPrice: 179999.99,
    discount: 20,
    isTrending: true,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: true,
    qty: 1,
  },
  // More variants for Nothing Phone 2 can be added here...
  //https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/0/i/n/-original-imagrdefzqhqqw5u.jpeg?q=70
  // Nothing Earphones - White
  {
    _id: "5",
    itemName: "Nothing PowerFul Earphones",
    image:
      "https://in.nothing.tech/cdn/shop/files/Personalised_Active_Noise_Cancellation_Desktop_1292x.png?v=1679371783",
    description: "Wireless earphones with exceptional sound quality.",
    rating: 4,
    reviews: 30,
    color: "White",
    battery: "2000mAh",
    category: "Earphones",
    oldPrice: 8989,
    newPrice: 7009.99,
    discount: 20,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false,
    qty: 1,
  },
  {
    _id: "6",
    itemName: "Nothing Premium Earphones",
    image:
      "https://in.nothing.tech/cdn/shop/files/Nothing_X_app_1292x.jpg?v=1679371781",
    description: "Wireless earphones with exceptional sound quality.",
    rating: 3.1,
    reviews: 30,
    color: "White",
    battery: "1200mAh",
    category: "Earphones",
    oldPrice: 8999.99,
    newPrice: 6999.99,
    discount: 22,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false,
    qty: 1,
  },
  // More variants for Nothing Earphones can be added here...

  // Nothing Earphones - Black
  {
    _id: "7",
    itemName: "Nothing Extreme Earphones",
    image:
      "https://in.nothing.tech/cdn/shop/files/ear-stick-03_1292x.jpg?v=1666611238",
    description: "Wireless earphones with exceptional sound quality.",
    rating: 4,
    reviews: 30,
    color: "Black",
    battery: "2000mAh",
    category: "Earphones",
    oldPrice: 2999.99,
    newPrice: 1999.99,
    discount: 20,
    isTrending: true,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: false,
    qty: 1,
  },
  // More variants for Nothing Earphones - Black can be added here...

  // Nothing Charger - White
  {
    _id: "8",
    itemName: "Nothing Torrent Charger",
    image:
      "https://in.nothing.tech/cdn/shop/products/AdapterIN_1292x.png?v=1657571682",
    description: "Fast charging wall adapter with a Type-C cable.",
    rating: 2.5,
    reviews: 25,
    color: "White",
    variant: "45W",
    category: "Accessories",
    oldPrice: 2500.99,
    newPrice: 2000.99,
    discount: 20,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,
    qty: 1,
  },
  {
    _id: "9",
    itemName: "Nothing Elite Charger",
    image:
      "https://in.nothing.tech/cdn/shop/files/Image_1280x1020_9987abcf-e3e8-4ca2-bdb3-7e63a32a7767_1292x.png?v=1658494793",
    description: "Fast charging wall adapter with a Type-C cable.",
    rating: 3.5,
    reviews: 25,
    color: "White",
    variant: "55W",
    category: "Accessories",
    oldPrice: 5999.99,
    newPrice: 5679.99,
    discount: 17,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,
    qty: 1,
  },
  // More variants for Nothing Charger - White can be added here...

  // Nothing Charger - Black
  {
    _id: "10",
    itemName: "Nothing Extreme Charger",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZQaaHvBbPce85CW0Fy93t0c7YvEjIwFbM2A&usqp=CAU",
    description: "Fast charging wall adapter with a Type-C cable.",
    rating: 4.5,
    reviews: 25,
    color: "Black",
    variant: "45W",
    category: "Accessories",
    oldPrice: 7898.99,
    newPrice: 6423.99,
    discount: 20,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,
    qty: 1,
  },
  // More variants for Nothing Charger - Black can be added here...

  // Nothing Charger - Black with cable
  {
    _id: "11",
    itemName: "Nothing Compact Charger",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-jmd8BuFnBjheLIVhGp06OY92_b17nHbDBA&usqp=CAU",
    description: "Fast charging wall adapter with a Type-C cable.",
    rating: 4.5,
    reviews: 25,
    color: "Black",
    variant: "55W",
    category: "Accessories",
    oldPrice: 5899.99,
    newPrice: 4999.99,
    discount: 17,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,
    qty: 1,
  },
  {
    _id: "12",
    itemName: "Nothing PowerFul Phone 2",
    image:
      "https://in.nothing.tech/cdn/shop/files/Phone-2-desktop-fotor-20230710124751_2_cd3fa297-4ccb-44e2-9bde-54a3d7916906.jpg?v=1688970887&width=1494",
    description: "An innovative smartphone with powerful specifications.",
    rating: 4.8,
    reviews: 40,
    color: "Black",
    storage: "12GB 256GB",
    category: "Mobile",
    oldPrice: 10999.99,
    newPrice: 89999.99,
    discount: 18,
    isTrending: false,
    inStock: false,
    delivery_time: "3-5 business days",
    fewLeft: true,
    qty: 1,
  },
  // More variants for Nothing Charger - Black with cable can be added here...
];
